
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 45;
  public static final int CIERRALLAVE = 39;
  public static final int PUNTOYCOMA = 44;
  public static final int ABRECORCHETE = 42;
  public static final int STORE = 10;
  public static final int ENTERO = 24;
  public static final int DIFERENTE = 29;
  public static final int INT = 15;
  public static final int FILTER = 13;
  public static final int ASTERISCO = 48;
  public static final int ARRAY = 19;
  public static final int UPDATE = 7;
  public static final int NOT = 36;
  public static final int MENORIGUAL = 33;
  public static final int AND = 34;
  public static final int IGUAL = 28;
  public static final int USE = 3;
  public static final int OR = 35;
  public static final int OBJECT = 20;
  public static final int BOOL = 17;
  public static final int ID = 27;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int DECIMAL = 25;
  public static final int TABLE = 4;
  public static final int TRUE = 22;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int EXPORT = 9;
  public static final int CADENA = 26;
  public static final int ADD = 6;
  public static final int NULL = 21;
  public static final int MENOR = 31;
  public static final int CIERRACORCHETE = 43;
  public static final int FIELDS = 12;
  public static final int ABREPAREN = 40;
  public static final int ASIGNACION = 37;
  public static final int MAYOR = 30;
  public static final int PUNTO = 47;
  public static final int ABRELLAVE = 38;
  public static final int READ = 5;
  public static final int FLOAT = 16;
  public static final int CLEAR = 8;
  public static final int DATABASE = 2;
  public static final int STRING = 18;
  public static final int AT = 11;
  public static final int FALSE = 23;
  public static final int CIERRAPAREN = 41;
  public static final int SET = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATABASE",
  "USE",
  "TABLE",
  "READ",
  "ADD",
  "UPDATE",
  "CLEAR",
  "EXPORT",
  "STORE",
  "AT",
  "FIELDS",
  "FILTER",
  "SET",
  "INT",
  "FLOAT",
  "BOOL",
  "STRING",
  "ARRAY",
  "OBJECT",
  "NULL",
  "TRUE",
  "FALSE",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID",
  "IGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "NOT",
  "ASIGNACION",
  "ABRELLAVE",
  "CIERRALLAVE",
  "ABREPAREN",
  "CIERRAPAREN",
  "ABRECORCHETE",
  "CIERRACORCHETE",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "COMA",
  "PUNTO",
  "ASTERISCO"
  };
}

